with 

source as (

    select * from "KNSDataLake"."deposco"."trading_partner"

),

cleaned as (

    select
         cast(TRADING_PARTNER_ID as bigint) as TRADING_PARTNER_ID,
         cast(VERSION as int) as VERSION,
         cast(CODE as varchar(40)) as CODE,
         cast(NAME as varchar(50)) as NAME,
         cast(CONTACT_FIRST_NAME as varchar(50)) as CONTACT_FIRST_NAME,
         cast(CONTACT_LAST_NAME as varchar(50)) as CONTACT_LAST_NAME,
         cast(CONTACT_PHONE as varchar(30)) as CONTACT_PHONE,
         cast(CONTACT_EMAIL as varchar(50)) as CONTACT_EMAIL,
         cast(LINE1 as varchar(64)) as LINE1,
         cast(LINE2 as varchar(64)) as LINE2,
         cast(LINE3 as varchar(64)) as LINE3,
         cast(LINE4 as varchar(64)) as LINE4,
         cast(CITY as varchar(30)) as CITY,
         cast(POSTAL_CODE as varchar(20)) as POSTAL_CODE,
         cast(DESCRIPTION as varchar(MAX)) as DESCRIPTION,
         cast(INDUSTRY as varchar(50)) as INDUSTRY,
         cast(TICKER as varchar(10)) as TICKER,
         cast(WEBSITE as varchar(50)) as WEBSITE,
         cast(ANNUAL_REVENUE as float) as ANNUAL_REVENUE,
         cast(ASSET_CARRYING_RATE_PERCENT as float) as ASSET_CARRYING_RATE_PERCENT,
         cast(DOING_BUSINESS_AS as varchar(50)) as DOING_BUSINESS_AS,
         cast(FAX_NUMBER as varchar(20)) as FAX_NUMBER,
         cast(NAICS as varchar(20)) as NAICS,
         cast(NUMBER_OF_EMPLOYEES as float) as NUMBER_OF_EMPLOYEES,
         cast(SIC as varchar(20)) as SIC,
         cast(ACCOUNT_NUMBER as varchar(30)) as ACCOUNT_NUMBER,
         cast(SCAC_PRO_NUMBER as varchar(9)) as SCAC_PRO_NUMBER,
         cast(UCCEAN_COMPANY_NUMBER as varchar(6)) as UCCEAN_COMPANY_NUMBER,
         cast(IATA_CODE as varchar(6)) as IATA_CODE,
         cast(PARTNERSHIP_TYPE as varchar(50)) as PARTNERSHIP_TYPE,
         cast(PARTNER_ACCOUNT_NUMBER as varchar(30)) as PARTNER_ACCOUNT_NUMBER,
         cast(TAXABLE as bit) as TAXABLE,
         cast(STATE_PROVINCE as varchar(100)) as STATE_PROVINCE,
         cast(COUNTRY as varchar(100)) as COUNTRY,
         cast(CREATED_DATE as datetime) as CREATED_DATE,
         cast(UPDATED_DATE as datetime) as UPDATED_DATE,
         cast(CREATED_BY_ID as bigint) as CREATED_BY_ID,
         cast(UPDATED_BY_ID as bigint) as UPDATED_BY_ID,
         cast(COMPANY_ID as bigint) as COMPANY_ID,
         cast(SEND_ASN as bit) as SEND_ASN,
         cast(REQUIRES_SHIPPING_AUTHORIZATION as bit) as REQUIRES_SHIPPING_AUTHORIZATION,
         cast(BILL_THIRD_PARTY as bit) as BILL_THIRD_PARTY,
         cast(UPS_ACCOUNT_NUMBER as varchar(100)) as UPS_ACCOUNT_NUMBER,
         cast(DROPSHIP_FEE as float) as DROPSHIP_FEE,
         cast(TRADING_PARTNER_PROFILE as varchar(200)) as TRADING_PARTNER_PROFILE,
         cast(FEDEX_ACCOUNT_NUMBER as varchar(10)) as FEDEX_ACCOUNT_NUMBER,
         cast(TAXPAYER_IDENTIFICATION_NUMBER as varchar(30)) as TAXPAYER_IDENTIFICATION_NUMBER,
         cast(USPS_ACCOUNT_NUMBER as varchar(50)) as USPS_ACCOUNT_NUMBER,
         cast(ENDICIA_ACCOUNT_NUMBER as varchar(100)) as ENDICIA_ACCOUNT_NUMBER,
         cast(SHIP_TO_ATTENTION as varchar(50)) as SHIP_TO_ATTENTION,
         cast(BILL_TO_FIRST_NAME as varchar(50)) as BILL_TO_FIRST_NAME,
         cast(BILL_TO_LAST_NAME as varchar(50)) as BILL_TO_LAST_NAME,
         cast(BILL_TO_PHONE as varchar(20)) as BILL_TO_PHONE,
         cast(BILL_TO_EMAIL as varchar(50)) as BILL_TO_EMAIL,
         cast(BILL_TO_LINE1 as varchar(64)) as BILL_TO_LINE1,
         cast(BILL_TO_LINE2 as varchar(64)) as BILL_TO_LINE2,
         cast(BILL_TO_LINE3 as varchar(64)) as BILL_TO_LINE3,
         cast(BILL_TO_LINE4 as varchar(64)) as BILL_TO_LINE4,
         cast(BILL_TO_CITY as varchar(30)) as BILL_TO_CITY,
         cast(BILL_TO_POSTAL_CODE as varchar(20)) as BILL_TO_POSTAL_CODE,
         cast(BILL_TO_FAX_NUMBER as varchar(20)) as BILL_TO_FAX_NUMBER,
         cast(BILL_TO_STATE_PROVINCE as varchar(100)) as BILL_TO_STATE_PROVINCE,
         cast(BILL_TO_COUNTRY as varchar(100)) as BILL_TO_COUNTRY,
         cast(BILL_TO_ATTENTION as varchar(50)) as BILL_TO_ATTENTION,
         cast(SHIP_VIA as varchar(20)) as SHIP_VIA,
         cast(CUSTOM_ATTRIBUTE1 as varchar(50)) as CUSTOM_ATTRIBUTE1,
         cast(CUSTOM_ATTRIBUTE2 as varchar(50)) as CUSTOM_ATTRIBUTE2,
         cast(CUSTOM_ATTRIBUTE3 as varchar(50)) as CUSTOM_ATTRIBUTE3,
         cast(CUSTOM_ATTRIBUTE4 as varchar(50)) as CUSTOM_ATTRIBUTE4,
         cast(PACKING_SLIP_REPORT as varchar(50)) as PACKING_SLIP_REPORT,
         cast(WAVE_PACKING_SLIP_REPORT as varchar(50)) as WAVE_PACKING_SLIP_REPORT,
         cast(TRADING_PARTNER_TYPE_ID as bigint) as TRADING_PARTNER_TYPE_ID,
         cast(RESOURCE_ID as bigint) as RESOURCE_ID,
         cast(FEDEX_METER_NUMBER as varchar(20)) as FEDEX_METER_NUMBER,
         cast(IMPORT_REFERENCE1 as varchar(50)) as IMPORT_REFERENCE1,
         cast(IMPORT_REFERENCE2 as varchar(50)) as IMPORT_REFERENCE2,
         cast(EXPORT_REFERENCE1 as varchar(50)) as EXPORT_REFERENCE1,
         cast(EXPORT_REFERENCE2 as varchar(50)) as EXPORT_REFERENCE2,
         cast(USE_SHIP_FROM_FOR_SHIPMENTS as bit) as USE_SHIP_FROM_FOR_SHIPMENTS,
         cast(PACKING_SLIP_LEVEL as varchar(50)) as PACKING_SLIP_LEVEL,
         cast(GROUP_ASN_BY as varchar(50)) as GROUP_ASN_BY,
         cast(GROUP_INV_BY as varchar(50)) as GROUP_INV_BY,
         cast(SSCC_NUMBERS_REQUIRED_FOR_TRIP as bit) as SSCC_NUMBERS_REQUIRED_FOR_TRIP,
         cast(PREVENT_PICK_TO_REUSED_PALLET as bit) as PREVENT_PICK_TO_REUSED_PALLET,
         cast(CALCULATE_CHECK_DIGIT as bit) as CALCULATE_CHECK_DIGIT,
         cast(FEDEX_USER_KEY as varchar(50)) as FEDEX_USER_KEY,
         cast(FEDEX_USER_PASSWORD as varchar(50)) as FEDEX_USER_PASSWORD,
         cast(REQUIRE_THIRD_PARTY_TERMS as bit) as REQUIRE_THIRD_PARTY_TERMS,
         cast(REQUIRE_COLLECT_TERMS as bit) as REQUIRE_COLLECT_TERMS,
         cast(REQUIRE_PREPAID_TERMS as bit) as REQUIRE_PREPAID_TERMS,
         cast(ZPL_LABEL_REPORT as varchar(50)) as ZPL_LABEL_REPORT,
         cast(SEQUENCE_SSCC_BY as varchar(15)) as SEQUENCE_SSCC_BY,
         cast(GROUP_PALLET_BY as varchar(30)) as GROUP_PALLET_BY,
         cast(TAX_RATE as float) as TAX_RATE,
         cast(PRICE_LIST_ID as int) as PRICE_LIST_ID,
         cast(QUALITY_CONTROL_PERCENT as float) as QUALITY_CONTROL_PERCENT,
         cast(USE_DENSITY_PRICING_FOR_UPS_FREIGHT as int) as USE_DENSITY_PRICING_FOR_UPS_FREIGHT,
         cast(ACCOUNT_STATUS as varchar(20)) as ACCOUNT_STATUS,
         cast(SSCC_EXPANSION_DIGIT as tinyint) as SSCC_EXPANSION_DIGIT,
         cast(TRANS_ROUTING_ENABLED as bit) as TRANS_ROUTING_ENABLED,
         cast(PAYMENT_TERMS as varchar(50)) as PAYMENT_TERMS,
         cast(EXPIRATION_THRESHOLD_IN_DAYS as int) as EXPIRATION_THRESHOLD_IN_DAYS,
         cast(MIN_ORDER_AMOUNT as float) as MIN_ORDER_AMOUNT,
         cast(RETAIL_PARTNER_CODE as varchar(50)) as RETAIL_PARTNER_CODE
  from source

)

select * from cleaned;